services:
  mysql-db:
    container_name: mysql-db
    image: mysql:8.4.6
    ports:
      - "3306:3306"
    networks:
      - my-app-network
    environment:
      - MYSQL_DATABASE=walletslotdb
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./mysql-data:/var/lib/mysql

  backend-app:
    container_name: backend-app
    image: docker.io/jeonhaeji/b108-container-registry:latest
    ports:
      - "8080:8080"
    depends_on:
      - mysql-db
    networks:
      - my-app-network
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/walletslotdb?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=${MYSQL_USER}
      - SPRING_DATASOURCE_PASSWORD=${MYSQL_PASSWORD}

# 서비스들이 사용할 네트워크
networks:
  my-app-network:
    driver: bridge